export const galleryData = [
  { id: 1, image: '/images/thumbnails/news-1.png', title: 'Kegiatan Gotong Royong', category: 'Kegiatan' },
  { id: 2, image: '/images/thumbnails/news-1.png', title: 'Pemandangan Sawah', category: 'Alam' },
  { id: 3, image: '/images/thumbnails/news-1.png', title: 'Acara Desa', category: 'Acara' },
  { id: 4, image: '/images/thumbnails/news-1.png', title: 'Infrastruktur Jalan', category: 'Infrastruktur' },
  { id: 5, image: '/images/thumbnails/news-1.png', title: 'Fasilitas Umum', category: 'Fasilitas' },
  { id: 6, image: '/images/thumbnails/news-1.png', title: 'Aktivitas Pertanian', category: 'Pertanian' },
  { id: 7, image: '/images/thumbnails/news-1.png', title: 'Upacara Adat', category: 'Budaya' },
  { id: 8, image: '/images/thumbnails/news-1.png', title: 'Anak-anak Bermain', category: 'Sosial' },
  { id: 9, image: '/images/thumbnails/news-1.png', title: 'Suasana Pasar', category: 'Ekonomi' },
  { id: 10, image: '/images/thumbnails/news-1.png', title: 'Kegiatan Olahraga', category: 'Olahraga' },
  { id: 11, image: '/images/thumbnails/news-1.png', title: 'Festival Desa', category: 'Festival' },
  { id: 12, image: '/images/thumbnails/news-1.png', title: 'Pemandangan Sore', category: 'Alam' },
  { id: 13, image: '/images/thumbnails/news-1.png', title: 'Rapat Desa', category: 'Pemerintahan' },
  { id: 14, image: '/images/thumbnails/news-1.png', title: 'Kegiatan Pemuda', category: 'Pemuda' },
  { id: 15, image: '/images/thumbnails/news-1.png', title: 'Tradisi Lokal', category: 'Budaya' },
  { id: 16, image: '/images/thumbnails/news-1.png', title: 'Pembangunan Desa', category: 'Pembangunan' },
  { id: 17, image: '/images/thumbnails/news-1.png', title: 'Kegiatan Edukasi', category: 'Pendidikan' },
  { id: 18, image: '/images/thumbnails/news-1.png', title: 'Perayaan Hari Besar', category: 'Perayaan' },
];
