export const potential = [
  {
    id: 1,
    category: 'Ekonomi',
    title: 'Pasar Desa Tegalsari',
    description: 'Pasar desa yang aktif menjadi pusat perekonomian masyarakat sekitar.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 2,
    category: 'Pariwisata',
    title: 'Wisata Gunung Bismo',
    description: 'Destinasi pendakian favorit dengan pemandangan alam yang memukau.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 3,
    category: 'Pertanian',
    title: 'Lahan Perkebunan Sayur',
    description: 'Lahan subur yang menghasilkan sayuran segar setiap musim.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 4,
    category: 'Kreatif',
    title: 'Kerajinan Tangan dari Bambu',
    description: 'Produk kerajinan lokal yang dibuat oleh masyarakat desa.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 5,
    category: 'Lestari',
    title: 'Hutan Lindung Desa',
    description: 'Wilayah hutan yang dijaga bersama untuk menjaga keseimbangan alam.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 6,
    category: 'Ekonomi',
    title: 'UMKM Makanan Khas',
    description: 'Usaha kecil menengah yang memproduksi makanan khas desa.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 7,
    category: 'Budaya',
    title: 'UMKM Makanan Khas',
    description: 'Usaha kecil menengah yang memproduksi makanan khas desa.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 8,
    category: 'Ekonomi',
    title: 'Pasar Desa Tegalsari',
    description: 'Pasar desa yang aktif menjadi pusat perekonomian masyarakat sekitar.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 9,
    category: 'Ekonomi',
    title: 'Pasar Desa Tegalsari',
    description: 'Pasar desa yang aktif menjadi pusat perekonomian masyarakat sekitar.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 10,
    category: 'Pariwisata',
    title: 'Wisata Gunung Bismo',
    description: 'Destinasi pendakian favorit dengan pemandangan alam yang memukau.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 11,
    category: 'Pariwisata',
    title: 'Wisata Gunung Bismo',
    description: 'Destinasi pendakian favorit dengan pemandangan alam yang memukau.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 12,
    category: 'Pariwisata',
    title: 'Wisata Gunung Bismo',
    description: 'Destinasi pendakian favorit dengan pemandangan alam yang memukau.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 13,
    category: 'Pariwisata',
    title: 'Wisata Gunung Bismo',
    description: 'Destinasi pendakian favorit dengan pemandangan alam yang memukau.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 14,
    category: 'Pertanian',
    title: 'Lahan Perkebunan Sayur',
    description: 'Lahan subur yang menghasilkan sayuran segar setiap musim.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 15,
    category: 'Pertanian',
    title: 'Lahan Perkebunan Sayur',
    description: 'Lahan subur yang menghasilkan sayuran segar setiap musim.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 16,
    category: 'Pertanian',
    title: 'Lahan Perkebunan Sayur',
    description: 'Lahan subur yang menghasilkan sayuran segar setiap musim.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 17,
    category: 'Pertanian',
    title: 'Lahan Perkebunan Sayur',
    description: 'Lahan subur yang menghasilkan sayuran segar setiap musim.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 18,
    category: 'Kreatif',
    title: 'Kerajinan Tangan dari Bambu',
    description: 'Produk kerajinan lokal yang dibuat oleh masyarakat desa.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 19,
    category: 'Kreatif',
    title: 'Kerajinan Tangan dari Bambu',
    description: 'Produk kerajinan lokal yang dibuat oleh masyarakat desa.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 20,
    category: 'Kreatif',
    title: 'Kerajinan Tangan dari Bambu',
    description: 'Produk kerajinan lokal yang dibuat oleh masyarakat desa.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 21,
    category: 'Kreatif',
    title: 'Kerajinan Tangan dari Bambu',
    description: 'Produk kerajinan lokal yang dibuat oleh masyarakat desa.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 22,
    category: 'Budaya',
    title: 'UMKM Makanan Khas',
    description: 'Usaha kecil menengah yang memproduksi makanan khas desa.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 23,
    category: 'Budaya',
    title: 'UMKM Makanan Khas',
    description: 'Usaha kecil menengah yang memproduksi makanan khas desa.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 24,
    category: 'Budaya',
    title: 'UMKM Makanan Khas',
    description: 'Usaha kecil menengah yang memproduksi makanan khas desa.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 25,
    category: 'Budaya',
    title: 'UMKM Makanan Khas',
    description: 'Usaha kecil menengah yang memproduksi makanan khas desa.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 26,
    category: 'Lestari',
    title: 'Hutan Lindung Desa',
    description: 'Wilayah hutan yang dijaga bersama untuk menjaga keseimbangan alam.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 27,
    category: 'Lestari',
    title: 'Hutan Lindung Desa',
    description: 'Wilayah hutan yang dijaga bersama untuk menjaga keseimbangan alam.',
    image: '/images/thumbnails/news-1.png',
  },
  {
    id: 28,
    category: 'Lestari',
    title: 'Hutan Lindung Desa',
    description: 'Wilayah hutan yang dijaga bersama untuk menjaga keseimbangan alam.',
    image: '/images/thumbnails/news-1.png',
  },
];
